### ISSUE TITLE
Sync the managed cluster location related labels to the kcp workloadcluster

### ISSUE THREAD

**Issue by skeeey** [stolostron/singapore#6]
Sync the managed cluster location related labels (e.g. the region,  platform and product etc.) to the kcp workloadcluster, then we can use this labels to locate the workloadclusters with KCP Location API

**Comment by robinbobbitt** [comment]
@skeeey please assign to me. I don't have permission to assign myself. Thanks!

**Comment by skeeey** [comment]
/assign @robinbobbitt 

I added you to the admin list of this repo
